package uk.gov.hmcts.reform.wataskmonitor.domain.taskmonitor;

public enum JobName {
    TERMINATION, INITIATION, CONFIGURATION, AD_HOC_DELETE_PROCESS_INSTANCES, AD_HOC_CREATE_TASKS,
    AD_HOC_UPDATE_CASE_DATA, AD_HOC_PENDING_TERMINATION_TASKS, TASK_INITIATION_FAILURES, TASK_TERMINATION_FAILURES,
    TASK_CLEAN_UP
}
