package uk.gov.hmcts.reform.wataskmonitor.domain.taskmonitor;

public enum JobName {
    TERMINATION, INITIATION, CONFIGURATION, AD_HOC_DELETE_PROCESS_INSTANCES, AD_HOC_CREATE_TASKS,
    AD_HOC_UPDATE_CASE_DATA, AD_HOC_PENDING_TERMINATION_TASKS
}
