targets:
  instance: ${TEST_URL:http://localhost:8077}
  camunda: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}
  wa-task-management-api:
    url: ${WA_TASK_MANAGEMENT_API_URL:http://localhost:8087}

idam:
  api:
    baseUrl: ${IDAM_URL:http://sidam-api}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://xui-webapp/oauth2/callback}
  scope: "openid profile roles"
  test:
    userCleanupEnabled: ${ENABLE_TEST_USER_DELETION:false}
    username: ${TEST_WA_LAW_FIRM_USERNAME:some_user@hmcts.net}
    password: ${TEST_WA_LAW_FIRM_PASSWORD:password}
  test-account-pw: ${IDAM_TEST_ACCOUNT_PW:default}

document_management:
  url: ${DM_STORE_URL:http://local-dm-store}

core_case_data:
  api:
    url: ${CCD_URL:http://ccd-data-store-api}

role-assignment-service:
  url: ${ROLE_ASSIGNMENT_URL:http://role-assignment}

spring:
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${WA_IDAM_CLIENT_ID:wa}
            client-secret: ${WA_IDAM_CLIENT_SECRET:something}

enable_initiation_trigger_flag: ${ENABLE_INITIATION_TRIGGER_FLAG:false}
